- name: "Add apt"
  command: "add-apt-repository ppa:longsleep/golang-backports"
- name: "Update apt cache"
  apt:
    update_cache: yes
    cache_valid_time: 600
    
- name: "Install dependencies"
  apt:
    name:
      - golang-go
    state: present